import { Router } from "express"; import { z } from "zod"; import { db } from "../lib/db.js"; import { randomToken,sha256 } from "../lib/crypto.js"; import { requireUser } from "../middleware/auth.js"; import { env,extensionIds } from "../config/env.js";import { decryptJson } from "../lib/crypto.js";import { revokeMeta } from "../services/meta.js";import { audit } from "../lib/audit.js";
export const extensionRouter=Router();
const callback=/^https:\/\/([a-p]{32})\.chromiumapp\.org\/callback$/;
function validRedirect(value:string){const match=value.match(callback);return !!match && extensionIds.includes(match[1]);}
extensionRouter.get("/authorize",async(req,res)=>{const parsed=z.string().url().safeParse(req.query.redirect_uri);if(!parsed.success||!validRedirect(parsed.data))return res.status(400).send("Extension redirect is not allowlisted");if(!req.session.userId){req.session.extensionRedirectUri=parsed.data;return res.redirect(`${env.WEB_URL}/login?returnTo=extension`);}const raw=randomToken();await db.extensionPairCode.create({data:{userId:req.session.userId!,codeHash:sha256(raw),redirectUri:parsed.data,expiresAt:new Date(Date.now()+5*60_000)}});const target=new URL(parsed.data);target.searchParams.set("code",raw);res.redirect(target.toString());});
extensionRouter.post("/token",async(req,res)=>{const parsed=z.object({code:z.string().min(20),redirectUri:z.string().url()}).safeParse(req.body);if(!parsed.success||!validRedirect(parsed.data.redirectUri))return res.status(400).json({error:"Invalid pair request"});const record=await db.extensionPairCode.findUnique({where:{codeHash:sha256(parsed.data.code)}});if(!record||record.consumedAt||record.expiresAt<new Date()||record.redirectUri!==parsed.data.redirectUri)return res.status(400).json({error:"Pair code is invalid or expired"});const raw=randomToken(40);await db.$transaction([db.extensionPairCode.update({where:{id:record.id},data:{consumedAt:new Date()}}),db.extensionToken.create({data:{userId:record.userId,tokenHash:sha256(raw),label:"Chrome/Edge extension",expiresAt:new Date(Date.now()+90*864e5)}})]);res.json({token:raw,expiresIn:90*86400});});
async function extensionUser(req:any,res:any,next:any){const raw=req.get("authorization")?.replace(/^Bearer\s+/i,"");if(!raw)return res.status(401).json({error:"Extension token required"});const token=await db.extensionToken.findUnique({where:{tokenHash:sha256(raw)}});if(!token||token.revokedAt||token.expiresAt<new Date())return res.status(401).json({error:"Extension token expired or revoked"});await db.extensionToken.update({where:{id:token.id},data:{lastUsedAt:new Date()}});req.extensionUserId=token.userId;req.extensionTokenId=token.id;next();}
extensionRouter.get("/status",extensionUser,async(req:any,res)=>{const [user,connection]=await Promise.all([db.user.findUnique({where:{id:req.extensionUserId},select:{name:true,email:true}}),db.facebookConnection.findFirst({where:{userId:req.extensionUserId,status:"ACTIVE"},select:{displayName:true,status:true,expiresAt:true}})]);res.json({appUser:user,facebook:connection});});
extensionRouter.post("/facebook/disconnect",extensionUser,async(req:any,res)=>{const connection=await db.facebookConnection.findFirst({where:{userId:req.extensionUserId,status:"ACTIVE"}});if(!connection)return res.status(404).json({error:"No active Facebook connection"});try{const {accessToken}=decryptJson<{accessToken:string}>(connection.encryptedAuthorizationData);await revokeMeta(accessToken)}catch{}await db.facebookConnection.delete({where:{id:connection.id}});await audit(req.extensionUserId,"FACEBOOK_DISCONNECTED","FacebookConnection","SUCCESS",connection.id,{source:"extension"});res.status(204).end();});
extensionRouter.post("/disconnect",extensionUser,async(req:any,res)=>{await db.extensionToken.update({where:{id:req.extensionTokenId},data:{revokedAt:new Date()}});res.status(204).end();});
